<a href="https://colab.research.google.com/github/Waseem-Gopang/Data-Science/blob/main/20SW022_Lab_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Task:01
#import numpy as np
#Using the Built-in functions you learned about in the previous lesson, create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive)

In [ ]:
import numpy as np
even_numbers = np.arange(2, 33, 2)
even_matrix = even_numbers.reshape(4, 4)
print(even_matrix)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


#Task: 02
#import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X =
# Use Boolean indexing to pick out only the odd numbers in the array
Y =

In [ ]:
import numpy as np
X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 != 0]

print("Original 5x5 array:")
print(X)

print("\nArray with only odd numbers:")
print(Y)


Original 5x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array with only odd numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


#Task:03
#import numpy as np
# Use Broadcasting to create a 4 x 4 ndarray that has its first column full of 1s, its second column full of 2s, its third column full of 3s, etc..

X =


In [ ]:
import numpy as np
X = np.arange(1, 5)[:, np.newaxis] * np.ones((4, 4), dtype=int)
print(X)


[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
